# Generated by Django 2.0.1 on 2018-01-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='gubun',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='name',
        ),
        migrations.AddField(
            model_name='userbook',
            name='url_refer',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
