# Generated by Django 2.0.1 on 2018-01-29 11:51

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0003_auto_20180129_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/user/', verbose_name='Image', width_field='width'),
        ),
    ]
