# Generated by Django 2.0.1 on 2018-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0005_auto_20180129_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_wiki',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
