# Generated by Django 2.0.1 on 2018-01-29 12:26

from django.db import migrations
import hoodpub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0006_user_url_wiki'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hoodpub.models.HoodpubUserManager()),
            ],
        ),
    ]
