# Generated by Django 2.0.1 on 2018-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0007_auto_20180129_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'url_wiki')},
        ),
    ]
