# Generated by Django 2.0.1 on 2018-02-02 12:18

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hoodpub', '0008_auto_20180129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=512, null=True, upload_to='images/user/', verbose_name='Image'),
        ),
    ]
